### ISSUE TITLE
Can't run test suite: FrozenError

### ISSUE THREAD

**Issue by 007lva** [denny/ShinyCMS-ruby#803]
I get this error on execute `rspec`:

```
An error occurred while loading ./spec/models/feature_flag_spec.rb.
Failure/Error: require File.expand_path( '../config/environment', __dir__ )

FrozenError:
  can't modify frozen #<Class:#<Array:0x000056523b277048>>: ["/home/......
```

**Comment by denny** [comment]
@007lva I think the problem here was around the Bugsnag gem, but I'm not sure; does it work better for you with the Gemfile layout I just merged?

**Comment by 007lva** [comment]
@denny still fails to me =(

**Comment by denny** [comment]
Hey @007lva; I installed a new laptop yesterday, so I had the opportunity to install the whole Ruby/Rails/ShinyCMS chain from scratch. It all worked okay here; is it possible your gems have got into a weird state or something? Can you possibly try a fresh install of rvm, Ruby, etc? I know it's a lot of hassle, but as I can't reproduce the problem here then I can't think of much else to suggest currently, sorry!

If you are still having trouble with a clean install, can you post the whole output of your test run and failure for me please?
